[package]
name = "lib-provider-openai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
framework-core.workspace = true
lib-provider.workspace = true
lib-web-core.workspace = true
types-admin.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures-util.workspace = true
reqwest = { workspace = true, features = ["json", "stream"] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
